# Generated by Django 5.1 on 2024-08-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0002_alter_decklisturl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBanlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banlist_date', models.CharField(max_length=200)),
            ],
        ),
    ]
